<?php

/**
 * apiBase 相当于api下的公共控制器。如果不需要登陆场景继承这个控制器
 * 需要登陆继承auth控制器
 */
namespace app\api\controller;


use app\BaseController;
use think\exception\HttpResponseException;

class ApiBase extends BaseController
{
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function show(...$args){
       throw new HttpResponseException(show(...$args));
    }
}