<?php


namespace app\api\controller;



class AuthBase extends ApiBase
{
    public $userId = 0;
    public $username = "";
    public $accessToken = "";

    protected function initialize()
    {
        //todo 补充中间件登陆，参考后台这块处理

        parent::initialize(); // TODO: Change the autogenerated stub
        $this->accessToken = $this->request->header("access-token");
        if(!$this->accessToken || !$this->isLogin()){
            return $this->show(config("status.not_login"), "没有登陆");
        }
    }

    /**判断用户是否登陆
     * @return bool
     */
    public function isLogin() {
        $userInfo = cache(config("redis.token_pre").$this->accessToken);
        if(!$userInfo){
            return false;
        }
        if (!empty($userInfo['id']) && !empty($userInfo['username'])) {
            $this->userId = $userInfo['id'];
            $this->username = $userInfo['username'];
            return true;
        }
        return false;
    }
}